name: ilhewl
description: A Flutter Music Player.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Audio related
  audiotagger: ^2.2.1
  audio_service: ^0.17.1
  audio_session: ^0.1.5
  just_audio: ^0.9.7
  on_audio_query: ^2.5.0


  # Productivity
  http: ^0.13.3
  dart_des: ^1.0.0
  share_plus: ^2.1.4
  device_info: ^2.0.2
  package_info: ^2.0.2
  url_launcher: ^6.0.10
  html_unescape: ^2.0.0
  webview_flutter: ^2.0.13
  # flutter_web_auth: ^0.3.0
  # flutter_downloader: ^1.6.1
  cached_network_image: ^3.1.0
  youtube_explode_dart: ^1.9.10
  flutter_forbidshot: 0.0.2
  image_picker: any
  open_file: any
  dio: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  provider: ^5.0.0


  # UI related
  cupertino_icons: ^1.0.3
  salomon_bottom_bar: ^3.1.0
  material_floating_search_bar: ^0.3.4
  material_design_icons_flutter: ^5.0.5955-rc.1
  miniplayer:
    git:
      url: https://github.com/Sangwan5688/miniplayer.git

  flutter_easyloading: ^3.0.0
  otp_text_field: ^1.1.1


  # Database related
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  
  # Storage related
  path_provider: ^2.0.3
  permission_handler: ^8.1.6
  file_picker: ^4.0.2
  flutter_windowmanager: ^0.2.0
  secure_application: ^3.7.3
  intl_phone_field: ^2.1.0
  intl: ^0.17.0
  otp_autofill: ^1.0.0
  pin_code_fields: ^7.3.0
  unicorndial: ^1.1.5
  multi_select_flutter: ^4.0.0
  flutter_cache_manager: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
